--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.2.921
--   Created On : Sunday, 15 June, 2014 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;


--  Drop Tables, Stored Procedures and Views 

DROP TABLE IF EXISTS artifact CASCADE;
DROP TABLE IF EXISTS beam CASCADE;
DROP TABLE IF EXISTS beam_log CASCADE;
DROP TABLE IF EXISTS beam_system CASCADE;
DROP TABLE IF EXISTS breakdown_category CASCADE;
DROP TABLE IF EXISTS breakdown_event CASCADE;
DROP TABLE IF EXISTS breakdown_status CASCADE;
DROP TABLE IF EXISTS element CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS experiment CASCADE;
DROP TABLE IF EXISTS facility CASCADE;
DROP TABLE IF EXISTS facility_logbook CASCADE;
DROP TABLE IF EXISTS facility_status CASCADE;
DROP TABLE IF EXISTS facility_status_event CASCADE;
DROP TABLE IF EXISTS log_change CASCADE;
DROP TABLE IF EXISTS log_entry CASCADE;
DROP TABLE IF EXISTS logbook CASCADE;
DROP TABLE IF EXISTS operations_role CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS resource CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS shift CASCADE;
DROP TABLE IF EXISTS shift_staff_member CASCADE;
DROP TABLE IF EXISTS shift_status CASCADE;
DROP TABLE IF EXISTS staff_member CASCADE;
DROP TABLE IF EXISTS staff_role CASCADE;
DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS user_preference CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;

--  Create Tables 
CREATE TABLE artifact
(
	artifact_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	type CHAR(1) NOT NULL COMMENT 'd - doc, t - trouble report, u - url',
	name VARCHAR(64) NOT NULL,
	log_entry INTEGER UNSIGNED NOT NULL,
	resource_id TEXT NOT NULL COMMENT 'resource identifier: URL, TR number, file name etc',
	description VARCHAR(255),
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (artifact_id),
	KEY (log_entry)

) ENGINE=InnoDB;


CREATE TABLE beam
(
	beam_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	beam_system INTEGER UNSIGNED NOT NULL,
	element INTEGER UNSIGNED NOT NULL,
	charge INTEGER NOT NULL,
	mass_number INTEGER NOT NULL,
	energy FLOAT(0) NOT NULL,
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (beam_id),
	KEY (beam_system),
	KEY (element)

) ENGINE=InnoDB COMMENT='each row is a beam';


CREATE TABLE beam_log
(
	beam_log_id INTEGER NOT NULL,
	occurred_at DATETIME NOT NULL,
	beam_system INTEGER UNSIGNED NOT NULL,
	beam INTEGER UNSIGNED,
	mass_number INTEGER,
	element INTEGER UNSIGNED,
	charge INTEGER,
	energy DOUBLE,
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (beam_log_id),
	KEY (beam),
	KEY (beam_system),
	KEY (element)

) ENGINE=InnoDB COMMENT='change in beam in a beam system';


CREATE TABLE beam_system
(
	beam_system_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(16) NOT NULL,
	facility INTEGER UNSIGNED NOT NULL,
	description VARCHAR(255),
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (beam_system_id),
	UNIQUE UQ_beam_system_name(name),
	KEY (facility)

) ENGINE=InnoDB COMMENT='a beam-related system in a facility';


CREATE TABLE breakdown_category
(
	brkcat_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Each row represents a system such as RF, Vaccuum, Cryo, Detector etc',
	name VARCHAR(64) NOT NULL,
	description VARCHAR(255) NOT NULL,
	parent INTEGER UNSIGNED,
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (brkcat_id),
	UNIQUE UQ_component_name(name)

) ENGINE=InnoDB;


CREATE TABLE breakdown_event
(
	brk_event_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	status INTEGER UNSIGNED NOT NULL DEFAULT '0' COMMENT '0 means system is down. 1 means up.',
	occurred_at DATETIME NOT NULL,
	facility INTEGER UNSIGNED NOT NULL,
	category INTEGER UNSIGNED NOT NULL,
	log_entry INTEGER UNSIGNED NOT NULL,
	experiment INTEGER UNSIGNED NOT NULL,
	modified_at DATETIME NOT NULL,
	modified_by VARCHAR(64) NOT NULL,
	version INTEGER NOT NULL DEFAULT 0 COMMENT 'For concurrency control',
	PRIMARY KEY (brk_event_id),
	KEY (experiment),
	KEY (category),
	KEY (facility),
	KEY (log_entry)

) ENGINE=InnoDB;


CREATE TABLE breakdown_status
(
	brkstat_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(16) NOT NULL,
	description VARCHAR(128) NOT NULL,
	PRIMARY KEY (brkstat_id)

) ENGINE=InnoDB;


CREATE TABLE element
(
	element_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	symbol VARCHAR(8) NOT NULL,
	name VARCHAR(128) NOT NULL,
	version INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'for concurrency control',
	PRIMARY KEY (element_id),
	UNIQUE UQ_element_symbol(symbol)

) ENGINE=InnoDB;


CREATE TABLE employee
(
	employee_id INTEGER UNSIGNED NOT NULL,
	first_name VARCHAR(128) NOT NULL,
	last_name VARCHAR(128) NOT NULL,
	login_id VARCHAR(32) COMMENT 'login name',
	nick_name VARCHAR(16) COMMENT 'shorter name',
	department VARCHAR(64),
	email VARCHAR(128),
	job INTEGER UNSIGNED,
	current_employee BOOL NOT NULL DEFAULT FALSE COMMENT 'current employee?',
	operations_staff BOOL NOT NULL DEFAULT FALSE COMMENT 'operations staff member?',
	sms_capable BOOL NOT NULL DEFAULT FALSE COMMENT 'can contact via sms?',
	sms_number VARCHAR(32),
	sms_provider INTEGER,
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (employee_id)

) ENGINE=InnoDB COMMENT='person who is or has been an employee';


CREATE TABLE experiment
(
	number INTEGER UNSIGNED NOT NULL,
	spokesperson VARCHAR(128),
	title VARCHAR(128),
	hours_approved INTEGER,
	hours_requested INTEGER,
	experiment_completed VARCHAR(3),
	description TEXT,
	a1900_contact VARCHAR(64),
	approval_date DATE,
	PAC SMALLINT,
	completion_date DATE,
	on_target_hours INTEGER,
	PRIMARY KEY (number)

) ENGINE=InnoDB;


CREATE TABLE facility
(
	facility_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	facility_name VARCHAR(32) NOT NULL,
	description VARCHAR(255) NOT NULL,
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (facility_id),
	UNIQUE UQ_facility_facility_name(facility_name)

) ENGINE=InnoDB;


CREATE TABLE facility_logbook
(
	fac_lb_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	facility INTEGER UNSIGNED NOT NULL,
	logbook INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (fac_lb_id)

) ENGINE=InnoDB COMMENT='each row is a logbook belonging to a facility';


CREATE TABLE facility_status
(
	status_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	description VARCHAR(255) NOT NULL,
	parent INTEGER UNSIGNED COMMENT 'statuses  have hierarchy. id of parent.',
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (status_id),
	UNIQUE UQ_fstatus_name(name),
	KEY (parent)

) ENGINE=InnoDB COMMENT='facility status';


CREATE TABLE facility_status_event
(
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	occurred_at DATETIME NOT NULL COMMENT 'time at which the status change occurred',
	facility INTEGER UNSIGNED NOT NULL,
	status INTEGER UNSIGNED NOT NULL,
	experiment INTEGER UNSIGNED NOT NULL,
	log_entry INTEGER UNSIGNED NOT NULL,
	modified_by VARCHAR(64) NOT NULL,
	modified_at DATETIME NOT NULL COMMENT 'time at which the record was modified',
	version INTEGER NOT NULL DEFAULT 0 COMMENT 'for concurrency control',
	PRIMARY KEY (id),
	KEY (experiment),
	KEY (facility),
	KEY (log_entry),
	KEY (status)

) ENGINE=InnoDB COMMENT='a change in a facility''s status';


CREATE TABLE log_change
(
	log_change_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	orig_log_entry INTEGER UNSIGNED NOT NULL,
	created_at DATETIME NOT NULL,
	notes TEXT NOT NULL,
	author INTEGER UNSIGNED NOT NULL,
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (log_change_id),
	KEY (author),
	KEY (orig_log_entry)

) ENGINE=InnoDB COMMENT='each row is a modification to a log entry';


CREATE TABLE log_entry
(
	log_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	logbook INTEGER UNSIGNED NOT NULL,
	created_at DATETIME NOT NULL,
	notes TEXT NOT NULL,
	author INTEGER UNSIGNED NOT NULL,
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (log_id),
	KEY (author),
	KEY (logbook)

) ENGINE=InnoDB COMMENT='Each row is a log entry';


CREATE TABLE logbook
(
	logbook_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	logbook_name VARCHAR(32) NOT NULL,
	facility INTEGER UNSIGNED NOT NULL,
	description VARCHAR(255) NOT NULL,
	default_log BOOL NOT NULL DEFAULT FALSE COMMENT 'default logbook for the facility',
	version INTEGER NOT NULL DEFAULT 0 COMMENT 'for concurrency control',
	PRIMARY KEY (logbook_id),
	UNIQUE UQ_logbook_logbook_name(logbook_name, facility),
	KEY (facility)

) ENGINE=InnoDB COMMENT='each row represents a facility''s logbook';


CREATE TABLE operations_role
(
	op_role_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	description VARCHAR(255),
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (op_role_id),
	UNIQUE UQ_job_name(name)

) ENGINE=InnoDB COMMENT='role of an operations staff member';


CREATE TABLE permission
(
	privilege_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	role INTEGER UNSIGNED NOT NULL,
	resource INTEGER UNSIGNED NOT NULL,
	oper CHAR(1) NOT NULL COMMENT 'Create,Update,Read,Delete,Login,Menu,Owner',
	version INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'for concurrency control',
	PRIMARY KEY (privilege_id),
	KEY (resource),
	KEY (role)

) ENGINE=InnoDB;


CREATE TABLE resource
(
	resource_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	description VARCHAR(255) NOT NULL,
	version INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'for optimistic concurrency control',
	PRIMARY KEY (resource_id),
	UNIQUE UQ_resource_name(name)

) ENGINE=InnoDB;


CREATE TABLE role
(
	role_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	role_name VARCHAR(64) NOT NULL,
	description VARCHAR(255) NOT NULL,
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (role_id),
	UNIQUE UQ_role_role_name(role_name)

) ENGINE=InnoDB;


CREATE TABLE shift
(
	shift_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	facility INTEGER UNSIGNED NOT NULL,
	start_time DATETIME NOT NULL,
	op_in_charge INTEGER UNSIGNED COMMENT 'operator in charge',
	exp_in_charge VARCHAR(128) COMMENT 'experimenter in charge',
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (shift_id),
	KEY (op_in_charge),
	KEY (facility)

) ENGINE=InnoDB COMMENT='each row is a shift of a facility';


CREATE TABLE shift_staff_member
(
	ssm_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	shift INTEGER UNSIGNED NOT NULL,
	staff_member INTEGER UNSIGNED NOT NULL,
	role INTEGER UNSIGNED NOT NULL,
	status INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (ssm_id),
	KEY (staff_member),
	KEY (role),
	KEY (shift),
	KEY (status)

) ENGINE=InnoDB COMMENT='a staff member on a shift';


CREATE TABLE shift_status
(
	status_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	description VARCHAR(255) NOT NULL,
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (status_id),
	UNIQUE UQ_shift_ostatus_name(name)

) ENGINE=InnoDB COMMENT='on shift status - on call, in house etc';


CREATE TABLE staff_member
(
	employee_id INTEGER UNSIGNED NOT NULL,
	job INTEGER UNSIGNED NOT NULL,
	can_sms BOOL NOT NULL DEFAULT FALSE,
	sms_number VARCHAR(32),
	sms_provider INTEGER,
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (employee_id)

) ENGINE=InnoDB COMMENT='an operation staff member';


CREATE TABLE staff_role
(
	staff_role_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	employee INTEGER UNSIGNED NOT NULL,
	role INTEGER UNSIGNED NOT NULL,
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (staff_role_id),
	KEY (employee),
	KEY (role)

) ENGINE=InnoDB COMMENT='role an operations staff member performs';


CREATE TABLE user
(
	user_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	login_id VARCHAR(32) NOT NULL,
	first_name VARCHAR(64) NOT NULL,
	last_name VARCHAR(64) NOT NULL,
	email VARCHAR(64) NOT NULL,
	comment VARCHAR(255),
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (user_id),
	UNIQUE UQ_user_login_id(login_id)

) ENGINE=InnoDB;


CREATE TABLE user_preference
(
	user_preference_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	user INTEGER UNSIGNED NOT NULL,
	name VARCHAR(64) NOT NULL,
	val VARCHAR(64),
	version INTEGER UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (user_preference_id),
	KEY (user)

) ENGINE=InnoDB COMMENT='a user preference';


CREATE TABLE user_role
(
	user_role_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	user INTEGER UNSIGNED NOT NULL,
	role INTEGER UNSIGNED NOT NULL,
	can_delegate BOOL NOT NULL DEFAULT false,
	is_role_manager BIGINT NOT NULL DEFAULT false,
	start_time TIMESTAMP,
	end_time TIMESTAMP,
	comment VARCHAR(255),
	version INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (user_role_id),
	KEY (user)

) ENGINE=InnoDB;



SET FOREIGN_KEY_CHECKS=1;


--  Create Foreign Key Constraints 
ALTER TABLE artifact ADD CONSTRAINT FK_artifact_log_entry 
	FOREIGN KEY (log_entry) REFERENCES log_entry (log_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE beam ADD CONSTRAINT FK_beam_beam_system 
	FOREIGN KEY (beam_system) REFERENCES beam_system (beam_system_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE beam ADD CONSTRAINT FK_beam_element 
	FOREIGN KEY (element) REFERENCES element (element_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE beam_log ADD CONSTRAINT FK_beam_log_beam 
	FOREIGN KEY (beam) REFERENCES beam (beam_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE beam_log ADD CONSTRAINT FK_beam_log_beam_system 
	FOREIGN KEY (beam_system) REFERENCES beam_system (beam_system_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE beam_log ADD CONSTRAINT FK_beam_log_element 
	FOREIGN KEY (element) REFERENCES element (element_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE beam_system ADD CONSTRAINT FK_beam_system_facility 
	FOREIGN KEY (facility) REFERENCES facility (facility_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE breakdown_event ADD CONSTRAINT FK_breakdown_event_experiment 
	FOREIGN KEY (experiment) REFERENCES experiment (number)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE breakdown_event ADD CONSTRAINT FK_breakdownt_status_component 
	FOREIGN KEY (category) REFERENCES breakdown_category (brkcat_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE breakdown_event ADD CONSTRAINT FK_breakdownt_status_facility 
	FOREIGN KEY (facility) REFERENCES facility (facility_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE breakdown_event ADD CONSTRAINT FK_breakdownt_status_log_entry 
	FOREIGN KEY (log_entry) REFERENCES log_entry (log_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE facility_status ADD CONSTRAINT fk_status_status 
	FOREIGN KEY (parent) REFERENCES facility_status (status_id);

ALTER TABLE facility_status_event ADD CONSTRAINT FK_facility_status_experiment 
	FOREIGN KEY (experiment) REFERENCES experiment (number)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE facility_status_event ADD CONSTRAINT FK_facility_status_facility 
	FOREIGN KEY (facility) REFERENCES facility (facility_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE facility_status_event ADD CONSTRAINT FK_facility_status_log_entry 
	FOREIGN KEY (log_entry) REFERENCES log_entry (log_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE facility_status_event ADD CONSTRAINT FK_facility_status_status 
	FOREIGN KEY (status) REFERENCES facility_status (status_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE log_change ADD CONSTRAINT FK_log_entry_mod_employee 
	FOREIGN KEY (author) REFERENCES employee (employee_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE log_change ADD CONSTRAINT FK_log_entry_mod_log_entry 
	FOREIGN KEY (orig_log_entry) REFERENCES log_entry (log_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE log_entry ADD CONSTRAINT FK_log_entry_employee 
	FOREIGN KEY (author) REFERENCES employee (employee_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE log_entry ADD CONSTRAINT FK_log_entry_logbook 
	FOREIGN KEY (logbook) REFERENCES logbook (logbook_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE logbook ADD CONSTRAINT FK_logbook_facility 
	FOREIGN KEY (facility) REFERENCES facility (facility_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE permission ADD CONSTRAINT FK_permission_resource 
	FOREIGN KEY (resource) REFERENCES resource (resource_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE permission ADD CONSTRAINT FK_priv_role 
	FOREIGN KEY (role) REFERENCES role (role_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE shift ADD CONSTRAINT FK_shift_employee 
	FOREIGN KEY (op_in_charge) REFERENCES employee (employee_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE shift ADD CONSTRAINT FK_shift_facility 
	FOREIGN KEY (facility) REFERENCES facility (facility_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE shift_staff_member ADD CONSTRAINT FK_shift_staff_member_employee 
	FOREIGN KEY (staff_member) REFERENCES employee (employee_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE shift_staff_member ADD CONSTRAINT FK_shift_staff_member_operations_role 
	FOREIGN KEY (role) REFERENCES operations_role (op_role_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE shift_staff_member ADD CONSTRAINT FK_shift_staff_member_shift 
	FOREIGN KEY (shift) REFERENCES shift (shift_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE shift_staff_member ADD CONSTRAINT FK_shift_staff_member_shift_ostatus 
	FOREIGN KEY (status) REFERENCES shift_status (status_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE staff_role ADD CONSTRAINT FK_staff_role_employee 
	FOREIGN KEY (employee) REFERENCES employee (employee_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE staff_role ADD CONSTRAINT FK_staff_role_operations_role 
	FOREIGN KEY (role) REFERENCES operations_role (op_role_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE user_preference ADD CONSTRAINT FK_user_preference_employee 
	FOREIGN KEY (user) REFERENCES employee (employee_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE user_role ADD CONSTRAINT FK_user_role_employee 
	FOREIGN KEY (user) REFERENCES employee (employee_id)
	ON DELETE RESTRICT ON UPDATE CASCADE;
